/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/signup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Signup */
    post: operations['signup_api_v1_auth_signup_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login */
    post: operations['login_api_v1_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Refresh */
    post: operations['refresh_api_v1_auth_refresh_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout */
    post: operations['logout_api_v1_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me */
    get: operations['me_api_v1_auth_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Users */
    get: operations['list_users_api_v1_users_get']
    put?: never
    /** Create User */
    post: operations['create_user_api_v1_users_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/users/{user_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get User */
    get: operations['get_user_api_v1_users__user_id__get']
    put?: never
    post?: never
    /** Deactivate User */
    delete: operations['deactivate_user_api_v1_users__user_id__delete']
    options?: never
    head?: never
    /** Update User */
    patch: operations['update_user_api_v1_users__user_id__patch']
    trace?: never
  }
  '/api/v1/shipments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Shipments */
    get: operations['list_shipments_api_v1_shipments_get']
    put?: never
    /** Create Shipment */
    post: operations['create_shipment_api_v1_shipments_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/shipments/{shipment_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Shipment */
    get: operations['get_shipment_api_v1_shipments__shipment_id__get']
    put?: never
    post?: never
    /** Delete Shipment */
    delete: operations['delete_shipment_api_v1_shipments__shipment_id__delete']
    options?: never
    head?: never
    /** Update Shipment */
    patch: operations['update_shipment_api_v1_shipments__shipment_id__patch']
    trace?: never
  }
  '/api/v1/suppliers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Suppliers */
    get: operations['list_suppliers_api_v1_suppliers_get']
    put?: never
    /** Create Supplier */
    post: operations['create_supplier_api_v1_suppliers_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/suppliers/{supplier_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Supplier */
    get: operations['get_supplier_api_v1_suppliers__supplier_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/suppliers/{supplier_id}/performance': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Supplier Performance */
    get: operations['supplier_performance_api_v1_suppliers__supplier_id__performance_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/documents': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Documents */
    get: operations['list_documents_api_v1_documents_get']
    put?: never
    /**
     * Upload Document
     * @description Accepts the file and hands it to a worker.
     *
     *     Parsing a large pdf takes tens of seconds, which is longer than a client or
     *     a proxy will wait, and a failed request would lose the upload entirely.
     */
    post: operations['upload_document_api_v1_documents_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/documents/{document_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Document */
    get: operations['get_document_api_v1_documents__document_id__get']
    put?: never
    post?: never
    /** Delete Document */
    delete: operations['delete_document_api_v1_documents__document_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/documents/{document_id}/chunks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Chunks */
    get: operations['get_chunks_api_v1_documents__document_id__chunks_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/documents/{document_id}/download': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Download Document */
    get: operations['download_document_api_v1_documents__document_id__download_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/documents/{document_id}/reprocess': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Reprocess Document */
    post: operations['reprocess_document_api_v1_documents__document_id__reprocess_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/alerts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Alerts */
    get: operations['list_alerts_api_v1_alerts_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/alerts/unread-count': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Unread Count */
    get: operations['unread_count_api_v1_alerts_unread_count_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/alerts/{alert_id}/read': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Mark Read */
    patch: operations['mark_read_api_v1_alerts__alert_id__read_patch']
    trace?: never
  }
  '/api/v1/alerts/read-all': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Mark All Read */
    post: operations['mark_all_read_api_v1_alerts_read_all_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/analytics/summary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Summary */
    get: operations['summary_api_v1_analytics_summary_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/analytics/shipments-by-status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** By Status */
    get: operations['by_status_api_v1_analytics_shipments_by_status_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/analytics/shipments-timeseries': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Timeseries */
    get: operations['timeseries_api_v1_analytics_shipments_timeseries_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/analytics/top-suppliers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Top Suppliers */
    get: operations['top_suppliers_api_v1_analytics_top_suppliers_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/analytics/risk-breakdown': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Risk Breakdown */
    get: operations['risk_breakdown_api_v1_analytics_risk_breakdown_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ask': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Ask */
    post: operations['ask_api_v1_ask_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/insights': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Insights */
    get: operations['list_insights_api_v1_insights_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * AlertKind
     * @enum {string}
     */
    AlertKind: 'late_delivery' | 'contract_expiry' | 'supplier_risk' | 'sla_breach'
    /** AlertRead */
    AlertRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      kind: components['schemas']['AlertKind']
      severity: components['schemas']['AlertSeverity']
      /** Title */
      title: string
      /** Body */
      body: string | null
      /** Entity Type */
      entity_type: string | null
      /** Entity Id */
      entity_id: string | null
      /** Is Read */
      is_read: boolean
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * AlertSeverity
     * @enum {string}
     */
    AlertSeverity: 'low' | 'medium' | 'high' | 'critical'
    /** AskRequest */
    AskRequest: {
      /** Question */
      question: string
      doc_type?: components['schemas']['DocType'] | null
      /** Document Ids */
      document_ids?: string[] | null
      /**
       * Top K
       * @default 8
       */
      top_k: number
    }
    /** AskResponse */
    AskResponse: {
      /** Question */
      question: string
      /** Answer */
      answer: string
      /** Route */
      route: string
      /**
       * Citations
       * @default []
       */
      citations: components['schemas']['Citation'][]
      /**
       * Filters
       * @default {}
       */
      filters: {
        [key: string]: unknown
      }
      /**
       * Shipments
       * @default []
       */
      shipments: components['schemas']['ShipmentRead'][]
      /** Model */
      model: string
      /** Total Ms */
      total_ms: number
    }
    /** Body_upload_document_api_v1_documents_post */
    Body_upload_document_api_v1_documents_post: {
      /** File */
      file: string
      doc_type: components['schemas']['DocType']
    }
    /** ChunkRead */
    ChunkRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Chunk Index */
      chunk_index: number
      /** Content */
      content: string
      /** Page No */
      page_no: number | null
      /** Token Count */
      token_count: number | null
      /** Meta */
      meta: {
        [key: string]: unknown
      }
    }
    /** Citation */
    Citation: {
      /** Number */
      number: number
      /**
       * Chunk Id
       * Format: uuid
       */
      chunk_id: string
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string
      /** Filename */
      filename: string | null
      /** Page No */
      page_no: number | null
      /** Section */
      section: string | null
      /** Score */
      score: number
    }
    /**
     * DocStatus
     * @enum {string}
     */
    DocStatus: 'pending' | 'processing' | 'indexed' | 'failed'
    /**
     * DocType
     * @enum {string}
     */
    DocType: 'contract' | 'manifest' | 'invoice'
    /** DocumentAccepted */
    DocumentAccepted: {
      /**
       * Document Id
       * Format: uuid
       */
      document_id: string
      status: components['schemas']['DocStatus']
      /** Job Id */
      job_id: string | null
    }
    /** DocumentRead */
    DocumentRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Filename */
      filename: string
      /** Content Type */
      content_type: string
      /** Size Bytes */
      size_bytes: number
      doc_type: components['schemas']['DocType']
      status: components['schemas']['DocStatus']
      /** Page Count */
      page_count: number | null
      /** Error */
      error: string | null
      /** Indexed At */
      indexed_at: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** DownloadLink */
    DownloadLink: {
      /** Url */
      url: string
      /** Expires In */
      expires_in: number
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** InsightRead */
    InsightRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Question */
      question: string
      /** Answer */
      answer: string
      /** Citations */
      citations: {
        [key: string]: unknown
      }[]
      /** Route */
      route: string
      /** Model */
      model: string | null
      /** Latency Ms */
      latency_ms: number | null
      /** Token In */
      token_in: number | null
      /** Token Out */
      token_out: number | null
      /** Created At */
      created_at: unknown
    }
    /** LoginRequest */
    LoginRequest: {
      /** Tenant Slug */
      tenant_slug: string
      /** Email */
      email: string
      /** Password */
      password: string
    }
    /** Page[AlertRead] */
    Page_AlertRead_: {
      /** Items */
      items: components['schemas']['AlertRead'][]
      /** Total */
      total: number
      /** Page */
      page: number
      /** Size */
      size: number
      /** Pages */
      readonly pages: number
    }
    /** Page[ChunkRead] */
    Page_ChunkRead_: {
      /** Items */
      items: components['schemas']['ChunkRead'][]
      /** Total */
      total: number
      /** Page */
      page: number
      /** Size */
      size: number
      /** Pages */
      readonly pages: number
    }
    /** Page[DocumentRead] */
    Page_DocumentRead_: {
      /** Items */
      items: components['schemas']['DocumentRead'][]
      /** Total */
      total: number
      /** Page */
      page: number
      /** Size */
      size: number
      /** Pages */
      readonly pages: number
    }
    /** Page[InsightRead] */
    Page_InsightRead_: {
      /** Items */
      items: components['schemas']['InsightRead'][]
      /** Total */
      total: number
      /** Page */
      page: number
      /** Size */
      size: number
      /** Pages */
      readonly pages: number
    }
    /** Page[ShipmentRead] */
    Page_ShipmentRead_: {
      /** Items */
      items: components['schemas']['ShipmentRead'][]
      /** Total */
      total: number
      /** Page */
      page: number
      /** Size */
      size: number
      /** Pages */
      readonly pages: number
    }
    /** Page[SupplierRead] */
    Page_SupplierRead_: {
      /** Items */
      items: components['schemas']['SupplierRead'][]
      /** Total */
      total: number
      /** Page */
      page: number
      /** Size */
      size: number
      /** Pages */
      readonly pages: number
    }
    /** Page[UserRead] */
    Page_UserRead_: {
      /** Items */
      items: components['schemas']['UserRead'][]
      /** Total */
      total: number
      /** Page */
      page: number
      /** Size */
      size: number
      /** Pages */
      readonly pages: number
    }
    /** RiskBreakdown */
    RiskBreakdown: {
      /** Items */
      items: components['schemas']['RiskSlice'][]
    }
    /**
     * RiskLabel
     * @enum {string}
     */
    RiskLabel: 'on_time' | 'at_risk' | 'delayed'
    /** RiskSlice */
    RiskSlice: {
      /** Label */
      label: string
      /** Shipments */
      shipments: number
    }
    /** ShipmentCreate */
    ShipmentCreate: {
      /** Reference */
      reference: string
      /** Supplier Id */
      supplier_id?: string | null
      /** Origin Country */
      origin_country: string
      /** Dest Country */
      dest_country: string
      mode: components['schemas']['TransportMode']
      /** Incoterm */
      incoterm?: string | null
      /**
       * Qty
       * @default 0
       */
      qty: number
      /**
       * Value Usd
       * @default 0
       */
      value_usd: number | string
      /** Weight Kg */
      weight_kg?: number | string | null
      /**
       * Eta
       * Format: date
       */
      eta: string
      /** Ata */
      ata?: string | null
      /** @default planned */
      status: components['schemas']['ShipmentStatus']
    }
    /** ShipmentRead */
    ShipmentRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Reference */
      reference: string
      /** Supplier Id */
      supplier_id: string | null
      /** Origin Country */
      origin_country: string
      /** Dest Country */
      dest_country: string
      mode: components['schemas']['TransportMode']
      /** Incoterm */
      incoterm: string | null
      /** Qty */
      qty: number
      /** Value Usd */
      value_usd: string
      /** Weight Kg */
      weight_kg: string | null
      /**
       * Eta
       * Format: date
       */
      eta: string
      /** Ata */
      ata: string | null
      status: components['schemas']['ShipmentStatus']
      risk_label: components['schemas']['RiskLabel'] | null
      /** Risk Score */
      risk_score: string | null
      /** Delay Days */
      delay_days: number | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * ShipmentStatus
     * @enum {string}
     */
    ShipmentStatus: 'planned' | 'in_transit' | 'delivered' | 'delayed' | 'cancelled'
    /** ShipmentUpdate */
    ShipmentUpdate: {
      /** Supplier Id */
      supplier_id?: string | null
      /** Incoterm */
      incoterm?: string | null
      /** Qty */
      qty?: number | null
      /** Value Usd */
      value_usd?: number | string | null
      /** Weight Kg */
      weight_kg?: number | string | null
      /** Eta */
      eta?: string | null
      /** Ata */
      ata?: string | null
      status?: components['schemas']['ShipmentStatus'] | null
    }
    /** SignupRequest */
    SignupRequest: {
      /** Company Name */
      company_name: string
      /** Tenant Slug */
      tenant_slug: string
      /** Email */
      email: string
      /** Password */
      password: string
      /** Full Name */
      full_name: string
    }
    /** StatusBreakdown */
    StatusBreakdown: {
      /** Items */
      items: components['schemas']['StatusCount'][]
    }
    /** StatusCount */
    StatusCount: {
      /** Status */
      status: string
      /** Shipments */
      shipments: number
      /** Value Usd */
      value_usd: string
    }
    /** Summary */
    Summary: {
      /** Total Shipments */
      total_shipments: number
      /** Delayed */
      delayed: number
      /** In Transit */
      in_transit: number
      /** Delivered */
      delivered: number
      /** Total Value Usd */
      total_value_usd: string
      /** On Time Rate */
      on_time_rate: number | null
      /** Avg Delay Days */
      avg_delay_days: number | null
      /**
       * Since
       * Format: date
       */
      since: string
    }
    /** SupplierCreate */
    SupplierCreate: {
      /** Name */
      name: string
      /** Country */
      country: string
      /** Category */
      category: string
      /** Contact Email */
      contact_email?: string | null
    }
    /** SupplierMonth */
    SupplierMonth: {
      /** Month */
      month: string
      /** Shipments */
      shipments: number
      /** Late */
      late: number
    }
    /** SupplierPerformance */
    SupplierPerformance: {
      /**
       * Supplier Id
       * Format: uuid
       */
      supplier_id: string
      /** Name */
      name: string
      /** Shipments */
      shipments: number
      /** Delivered */
      delivered: number
      /** Late */
      late: number
      /** On Time Rate */
      on_time_rate: number | null
      /** Avg Delay Days */
      avg_delay_days: number | null
      /** Monthly */
      monthly: components['schemas']['SupplierMonth'][]
    }
    /** SupplierRanking */
    SupplierRanking: {
      /** Supplier Id */
      supplier_id: string
      /** Name */
      name: string
      /** Shipments */
      shipments: number
      /** Late */
      late: number
      /** On Time Rate */
      on_time_rate: number | null
    }
    /** SupplierRead */
    SupplierRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /** Country */
      country: string
      /** Category */
      category: string
      /** Contact Email */
      contact_email: string | null
      /** On Time Rate */
      on_time_rate: string | null
      /** Risk Score */
      risk_score: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /** Timeseries */
    Timeseries: {
      /** Items */
      items: components['schemas']['TimeseriesPoint'][]
    }
    /** TimeseriesPoint */
    TimeseriesPoint: {
      /** Month */
      month: string
      /** Shipments */
      shipments: number
      /** Late */
      late: number
      /** Value Usd */
      value_usd: string
    }
    /** TokenResponse */
    TokenResponse: {
      /** Access Token */
      access_token: string
      /**
       * Token Type
       * @default bearer
       */
      token_type: string
      /** Expires In */
      expires_in: number
      role: components['schemas']['UserRole']
      /** Tenant Slug */
      tenant_slug: string
    }
    /** TopSuppliers */
    TopSuppliers: {
      /** Items */
      items: components['schemas']['SupplierRanking'][]
    }
    /**
     * TransportMode
     * @enum {string}
     */
    TransportMode: 'air' | 'ocean' | 'road' | 'rail'
    /** UserCreate */
    UserCreate: {
      /** Email */
      email: string
      /** Password */
      password: string
      /** Full Name */
      full_name: string
      role: components['schemas']['UserRole']
    }
    /**
     * UserRead
     * @description Fields are listed explicitly so password_hash cannot leak by accident.
     */
    UserRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Email */
      email: string
      /** Full Name */
      full_name: string
      role: components['schemas']['UserRole']
      /** Is Active */
      is_active: boolean
      /** Last Login At */
      last_login_at: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
    }
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: 'admin' | 'analyst' | 'viewer'
    /** UserUpdate */
    UserUpdate: {
      /** Full Name */
      full_name?: string | null
      role?: components['schemas']['UserRole'] | null
      /** Is Active */
      is_active?: boolean | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  signup_api_v1_auth_signup_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SignupRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        refresh_token?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: {
        refresh_token?: string | null
      }
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  me_api_v1_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRead']
        }
      }
    }
  }
  list_users_api_v1_users_get: {
    parameters: {
      query?: {
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_UserRead_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_user_api_v1_users_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_user_api_v1_users__user_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  deactivate_user_api_v1_users__user_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_user_api_v1_users__user_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_shipments_api_v1_shipments_get: {
    parameters: {
      query?: {
        page?: number
        size?: number
        status?: components['schemas']['ShipmentStatus'] | null
        mode?: components['schemas']['TransportMode'] | null
        risk_label?: components['schemas']['RiskLabel'] | null
        supplier_id?: string | null
        origin_country?: string | null
        dest_country?: string | null
        eta_from?: string | null
        eta_to?: string | null
        late_only?: boolean
        search?: string | null
        sort?: 'created_at' | 'eta' | 'value_usd' | 'reference'
        order?: 'asc' | 'desc'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_ShipmentRead_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_shipment_api_v1_shipments_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ShipmentCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ShipmentRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_shipment_api_v1_shipments__shipment_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        shipment_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ShipmentRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_shipment_api_v1_shipments__shipment_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        shipment_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_shipment_api_v1_shipments__shipment_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        shipment_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ShipmentUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ShipmentRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_suppliers_api_v1_suppliers_get: {
    parameters: {
      query?: {
        page?: number
        size?: number
        country?: string | null
        category?: string | null
        search?: string | null
        sort?: 'name' | 'on_time_rate' | 'risk_score' | 'created_at'
        order?: 'asc' | 'desc'
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_SupplierRead_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_supplier_api_v1_suppliers_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SupplierCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SupplierRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_supplier_api_v1_suppliers__supplier_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        supplier_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SupplierRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  supplier_performance_api_v1_suppliers__supplier_id__performance_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        supplier_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SupplierPerformance']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_documents_api_v1_documents_get: {
    parameters: {
      query?: {
        page?: number
        size?: number
        doc_type?: components['schemas']['DocType'] | null
        status?: components['schemas']['DocStatus'] | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_DocumentRead_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  upload_document_api_v1_documents_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_document_api_v1_documents_post']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DocumentAccepted']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_document_api_v1_documents__document_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        document_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DocumentRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_document_api_v1_documents__document_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        document_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_chunks_api_v1_documents__document_id__chunks_get: {
    parameters: {
      query?: {
        page?: number
        size?: number
      }
      header?: never
      path: {
        document_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_ChunkRead_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  download_document_api_v1_documents__document_id__download_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        document_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DownloadLink']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  reprocess_document_api_v1_documents__document_id__reprocess_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        document_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DocumentAccepted']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_alerts_api_v1_alerts_get: {
    parameters: {
      query?: {
        page?: number
        size?: number
        kind?: components['schemas']['AlertKind'] | null
        severity?: components['schemas']['AlertSeverity'] | null
        unread_only?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_AlertRead_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  unread_count_api_v1_alerts_unread_count_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: number
          }
        }
      }
    }
  }
  mark_read_api_v1_alerts__alert_id__read_patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        alert_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AlertRead']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  mark_all_read_api_v1_alerts_read_all_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: number
          }
        }
      }
    }
  }
  summary_api_v1_analytics_summary_get: {
    parameters: {
      query?: {
        /** @description Days of history to include */
        days?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Summary']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  by_status_api_v1_analytics_shipments_by_status_get: {
    parameters: {
      query?: {
        /** @description Days of history to include */
        days?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StatusBreakdown']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  timeseries_api_v1_analytics_shipments_timeseries_get: {
    parameters: {
      query?: {
        /** @description Days of history to include */
        days?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Timeseries']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  top_suppliers_api_v1_analytics_top_suppliers_get: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TopSuppliers']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  risk_breakdown_api_v1_analytics_risk_breakdown_get: {
    parameters: {
      query?: {
        /** @description Days of history to include */
        days?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RiskBreakdown']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  ask_api_v1_ask_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AskRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AskResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_insights_api_v1_insights_get: {
    parameters: {
      query?: {
        page?: number
        size?: number
        route?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_InsightRead_']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
}
